
include ../../../base.make

MODULE = "$\
    tests.stimulis_inputs.main,$\
    tests.unit_write_read.main,$\
    tests.file_write_read.main$\
"

include $(shell cocotb-config --makefiles)/Makefile.sim
