
include ../../base.make

MODULE = "$\
	tests.dma_copy.main,$\
	tests.file_write.main,$\
	tests.file_read.main,$\
	tests.ram_from_to_file.main,$\
	tests.random_stimulis.main,$\
	tests.special_cases.main,$\
	tests.little_file_write.main$\
"

include $(shell cocotb-config --makefiles)/Makefile.sim
